---
title: "class practice"
author: "Justin Markey"
date: "9/13/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#import data
```{r}
data <- read.csv("class practice sep-13.csv")

```

```{r}
with (data,
      boxplot(X1))
```

#define range
```{r}
bottomq<-with(data,quantile(X1,0.01,na.rm=TRUE))
topq<-with(data,quantile(X1,0.99,na.rm=TRUE))
```

#identify outliers

```{r}

data$outlier.label<-with(data,
                          ifelse(X1>topq,"Outlier",
                           ifelse(X1<bottomq,"Outlier","Normal Data")))
subset(data,outlier.label=="Outlier")

```

#winsorize

```{r}
data$X1.Winsorized<-with(data,
                          ifelse(X1>topq,topq,
                           ifelse(X1<bottomq,bottomq,X1)))
```

#imputation
```{r}
unconditional.mean<-with(data,mean(data$X1.Winsorized,na.rm=TRUE))
```

#replace
```{r}
data$X1.Winsorized.Imputed<-with(data,
     ifelse(is.na(X1.Winsorized),
       unconditional.mean,
       X1.Winsorized))
```
#check cleaned data
```{r}
summary(data$X1.Winsorized.Imputed)
```

#conditional mean
```{r}
mean.A<-with(subset(data,X2=="A"),
                mean(X1.Winsorized,na.rm=TRUE))
mean.B<-with(subset(data,X2=="B"),
                mean(X1.Winsorized,na.rm=TRUE))
```

```{r}
data$X1.Winsorized.Imputed.V2<-with(data,
ifelse(
  is.na(X1.Winsorized)&X2=="A",
  mean.A,
  ifelse(
    is.na(X1.Winsorized)&X2=="B",
    mean.B,
    X1.Winsorized
  )
)
)
```

```{r}
summary(data)
```


